version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dazhy
      POSTGRES_PASSWORD: dazhy
      POSTGRES_DB: short_link
    ports:
      - "1234:1234"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
