// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type ShortLink struct {
	ID           int32
	OriginalUrl  string
	ShortenedUrl string
	CreatedAt    sql.NullTime
}
