// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
)

const createShortURL = `-- name: CreateShortURL :exec
INSERT INTO short_links (original_url, shortened_url)
VALUES ($1, $2)
`

type CreateShortURLParams struct {
	OriginalUrl  string
	ShortenedUrl string
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) error {
	_, err := q.db.ExecContext(ctx, createShortURL, arg.OriginalUrl, arg.ShortenedUrl)
	return err
}

const existsURL = `-- name: ExistsURL :one
SELECT shortened_url
FROM short_links
WHERE original_url = $1
`

func (q *Queries) ExistsURL(ctx context.Context, originalUrl string) (string, error) {
	row := q.db.QueryRowContext(ctx, existsURL, originalUrl)
	var shortened_url string
	err := row.Scan(&shortened_url)
	return shortened_url, err
}

const getOriginalURL = `-- name: GetOriginalURL :one
SELECT original_url
FROM short_links
WHERE shortened_url = $1
`

func (q *Queries) GetOriginalURL(ctx context.Context, shortenedUrl string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOriginalURL, shortenedUrl)
	var original_url string
	err := row.Scan(&original_url)
	return original_url, err
}
